version: "3.8"
services:
  backend:
    image: "moisesvinajera/springboot-react-fullstack:4.11.2021.17.58.24"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
