version: "3.8"
services:
  backend:
    image: "moisesvinajera/springboot-react-fullstack:6.12.2021.19.23.56"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
