version: "3.8"
services:
  backend:
    image: "moisesvinajera/springboot-react-fullstack:3.11.2021.22.2.51"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
